---
files:
  pages:
    - 'abcoasters.md'
    - 'about.md'
    - 'abseries.md'
    - 'beyond.md'
    - 'index.md'
    - 'links.md'
    - 'music.md'
    - 'notes.md'
    - 'programme.md'
    - 'stepsheets.md'
  data:
    - '_data/singlevideos.csv'
    - '_data/videos.csv'
  config:
    - '_config.yml'
generator: 'jekyll'
git:
  type: 'local'
  targets:
    live:
      push-option: "prod"
      url: "https://www.vmyers.com/"
    test:
      push-option: "test"
      url: "https://www.vmyers.com/test/"
