---
files:
  pages:
    - 'abcoasters.md'
    - 'about.md'
    - 'abseries.md'
    - 'beyond.md'
    - 'index.md'
    - 'links.md'
    - 'music.md'
    - 'notes.md'
    - 'programme.md'
    - 'stepsheets.md'
  data:
    - '_data/singlevideos.csv'
    - '_data/videos.csv'
  config:
    - '_config.yml'
generator: "jekyll"
