---
files:
  pages:
    - 'about.md'
    - 'example.md'
    - 'help.md'
    - 'index.md'
  notes:
    - 'fixme.txt'
generator: "banana"
git:
  type: 'local'
  targets:
    live:
      push-option: "prod"
      url: "https://www.example.com/"
    test:
      push-option: "test"
      url: "https://test.example.com/"
